import { AdminType } from './enums';

export enum Permission {
  VIEW_APPLICATION_QUEUE = 'VIEW_APPLICATION_QUEUE',
  VERIFY_DOCUMENTS = 'VERIFY_DOCUMENTS',
  APPROVE_REJECT_APPLICATIONS = 'APPROVE_REJECT_APPLICATIONS',
  ADD_REMARKS = 'ADD_REMARKS',
  ALLOCATE_SCHOLARSHIP = 'ALLOCATE_SCHOLARSHIP',
  EXPORT_REPORTS = 'EXPORT_REPORTS',
  VIEW_ADMIN_DASHBOARD = 'VIEW_ADMIN_DASHBOARD',
  VIEW_OWN_AUDIT_TRAIL = 'VIEW_OWN_AUDIT_TRAIL',
  MANAGE_OPERATORS = 'MANAGE_OPERATORS',
  CREATE_SUPER_ADMIN = 'CREATE_SUPER_ADMIN',
  VIEW_FULL_AUDIT_LOGS = 'VIEW_FULL_AUDIT_LOGS',
  SYSTEM_SETTINGS = 'SYSTEM_SETTINGS',
  DELETE_APPLICATIONS = 'DELETE_APPLICATIONS',
  REOPEN_REJECTED_APPLICATIONS = 'REOPEN_REJECTED_APPLICATIONS',
}

const OPERATOR_PERMISSIONS: Permission[] = [
  Permission.VIEW_APPLICATION_QUEUE,
  Permission.VERIFY_DOCUMENTS,
  Permission.APPROVE_REJECT_APPLICATIONS,
  Permission.ADD_REMARKS,
  Permission.ALLOCATE_SCHOLARSHIP,
  Permission.EXPORT_REPORTS,
  Permission.VIEW_ADMIN_DASHBOARD,
  Permission.VIEW_OWN_AUDIT_TRAIL,
];

const SUPER_PERMISSIONS: Permission[] = [
  ...OPERATOR_PERMISSIONS,
  Permission.MANAGE_OPERATORS,
  Permission.CREATE_SUPER_ADMIN,
  Permission.VIEW_FULL_AUDIT_LOGS,
  Permission.SYSTEM_SETTINGS,
  Permission.DELETE_APPLICATIONS,
  Permission.REOPEN_REJECTED_APPLICATIONS,
];

export const ADMIN_PERMISSIONS: Record<AdminType, Permission[]> = {
  [AdminType.SUPER]: SUPER_PERMISSIONS,
  [AdminType.OPERATOR]: OPERATOR_PERMISSIONS,
};

export function hasPermission(
  adminType: AdminType,
  permission: Permission,
): boolean {
  return ADMIN_PERMISSIONS[adminType].includes(permission);
}
