export enum UserRole {
  STUDENT = 'STUDENT',
  ADMIN = 'ADMIN',
}

export enum AdminType {
  SUPER = 'SUPER',
  OPERATOR = 'OPERATOR',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ALLOCATED = 'ALLOCATED',
}

export enum Caste {
  GEN = 'GEN',
  SC = 'SC',
  ST_P = 'ST_P',
  ST_H = 'ST_H',
  OBC = 'OBC',
  MOBC = 'MOBC',
}

export enum ResidenceType {
  HOSTELER = 'HOSTELER',
  DAY_SCHOLAR = 'DAY_SCHOLAR',
}

export enum DocumentType {
  STUDENT_ID_CARD = 'STUDENT_ID_CARD',
  ADMISSION_RECEIPT = 'ADMISSION_RECEIPT',
  AADHAAR_STUDENT = 'AADHAAR_STUDENT',
  VOTER_ID_STUDENT = 'VOTER_ID_STUDENT',
  NRC_FINAL_DRAFT = 'NRC_FINAL_DRAFT',
  BANK_ACCOUNT_DETAILS = 'BANK_ACCOUNT_DETAILS',
  PARENT_AADHAAR = 'PARENT_AADHAAR',
  FULL_PHOTO_WITH_APRON = 'FULL_PHOTO_WITH_APRON',
  COURSE_YEARLY_EXPENSE = 'COURSE_YEARLY_EXPENSE',
  HOSTEL_PAYMENT_RECEIPT = 'HOSTEL_PAYMENT_RECEIPT',
  BPL_CERTIFICATE = 'BPL_CERTIFICATE',
  INCOME_CERTIFICATE = 'INCOME_CERTIFICATE',
}

export enum DocumentVerificationStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum ScholarshipType {
  ONE_TIME = 'ONE_TIME',
  YEARLY = 'YEARLY',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PARTIAL = 'PARTIAL',
  PAID = 'PAID',
}

export enum PaymentType {
  YEARLY = 'YEARLY',
  SEMESTER = 'SEMESTER',
  ONE_TIME = 'ONE_TIME',
}

export enum RemarkAction {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  DOCUMENT_REJECTED = 'DOCUMENT_REJECTED',
  ALLOCATION_CREATED = 'ALLOCATION_CREATED',
  REALLOCATED = 'REALLOCATED',
}
